### ISSUE TITLE
enabling tilt / pressing buttons causes grid to disconnect

### ISSUE THREAD

**Issue by el-quinto** [monome/libmonome#80]
Windows 10, SerialOSC 1.4.4

Enabling tilt causes the grid to become disconnected by itself in about a minute or two. The issue occurs with both my 2012 edition 256 and 64.

<pre><code>
----------begin_max5_patcher----------
455.3ocmTssaiBCD8YhT9Gr7yzFtjM6kekUqVYLSIt0XirMzzsZ+2WaOPDjP
Zi1GvFNy0Cmw98saRnU5SfkR9A4mjjj28HIQr.RxDPBskchKY1niTE7pt5YZ
5nMGbxEw6LBk6LrpuU26jfKFT1DrnN5qOAOr+rucLG+nP07aCvcXyT78GyRI
44eIrUVDVK7qjeMK+B0T5yif+c6lvteK8tISKXsrF3Z1rqUqzsvNmP51YAGI
ijeCxkuB4J+bxU7UjhkWSNL4t25.L.J8FDu3+l3Uw9BLm6yAA75fvJpDRg6s
E7R+zS9+.XqjE51r4MqTyeApqMrFK2nkxE5MWJ3u3NZz8MGWX.TrJIbbkPPK
CqXAqjU7GXAbUSqt9BHso1ys4PK0rCqnY4etlcXeTrxiRW49OVyRIz3IB70y
OyjRVKfSgwYsGpgAAGdzqS9FftpfWdgfiIiJEpqNFGIQvvEiAVcugO0ji7lL
iH0f0ITLmPql4zdzoaOuc2kq7dJW9pkajsrttAvXGi.qje59YcTw+VJ9sPge
iRM0.goaLjBDhY7pryKw8FTGNcX7RIZXhxn5ES2tD3ZnzwCPAcy1wPVEOnsc
i2g+A7Re0XB
-----------end_max5_patcher-----------
</code></pre>

**Comment by artfwo** [comment]
hey @el-quinto , @tehn !

so it seems that the original issue happens when windows version of `monome_platform_read` reads less bytes than requested - it can happen for any mext events, presumably non-mext too.

while a simple solution would be augment `monome_platform_read` with a loop that keeps reading data from the port if we got less data than requested, it doesn't work well when the data on the serial port isn't available yet (the function then requires waits between consecutive reads).

a proper solution would be to implement `monome_platform_wait_for_input` on windows similar to [wait_for_serial_input](https://github.com/monome/serialosc/blob/083c15dbc2eae51bfeeb395631b0b5109b537762/src/serialosc-device/event_loop/windows.c#L74) in serialosc, and rewrite `monome_platform_read` accordingly, so it would try to fill output buffer as the data comes in (see [monome_platform_read](https://github.com/monome/libmonome/blob/main/src/platform/posix.c#L168) in `posix.c`)

i'll give it a go next week and let you know how that goes!

**Comment by tehn** [comment]
thanks @artfwo !

i just glanced at the libmonome protocol source, and it seems the the "series" protocol doesn't have packet payload lengths, similar to mext: https://github.com/monome/libmonome/blob/main/src/proto/mext.h#L149

not sure if that's helpful for anticipating complete packet reception prior to attempting to process a packet (the firmware does this in the other direction)

**Comment by artfwo** [comment]
> which is to say--- i can add packet lengths for older protocols if that helps!

it shouldn't be necessary -- older protocols still use `monome_platform_read` with known packet lengths, so we only need to fix `monome_platform_read` on windows to fix them all.

**Comment by el-quinto** [comment]
thanks @artfwo !

**Comment by artfwo** [comment]
ok, so this should be fixed in serialosc 1.4.5:

https://github.com/monome/serialosc/releases/tag/v1.4.5

thanks @el-quinto for testing!

**Comment by tehn** [comment]
thank you @artfwo !!
